package UI;

import DAO.TongVeThangDAO;
import DAO.VeThangDAO;
import DTO.TongVeThangDTO;
import DTO.VeThangDTO;
import UI.HoaDonVT.BillActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author quang
 */
public class DangKyVeThang extends javax.swing.JFrame {

    private String ten;
    DefaultTableModel tableModel;
    List<VeThangDTO> dataList = new ArrayList<>();

    public DangKyVeThang(String tenNhanVien) {
        this.ten = tenNhanVien;
        initComponents();
        chaoMungTxt.setText(tenNhanVien + " !");
        tableModel = (DefaultTableModel) veTable.getModel();
        showData();
        veTable.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int index = veTable.getSelectedRow();
                VeThangDTO ticket = dataList.get(index);
                maVeTxt.setText(ticket.getMaVe());
                tenKHTxt.setText(ticket.getTenKhach());
                sdtTxt.setText(ticket.getSdt());
                biensoXeTxt.setText(ticket.getBienSo());
                loaiXeTxt.setText(ticket.getLoaiXe());
                mauXeTxt.setText(ticket.getMauXe());
                xoaBtn.setEnabled(true);
                suaBtn.setEnabled(true);
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }

        });
    }

    private void showData() {
        dataList = VeThangDAO.findAll();

        tableModel.setRowCount(0);

        for (VeThangDTO ticket : dataList) {
            tableModel.addRow(new Object[]{
                ticket.getMaVe(),
                ticket.getTenKhach(),
                ticket.getSdt(),
                ticket.getBienSo(),
                ticket.getLoaiXe(),
                ticket.getMauXe(),
                ticket.getNgayDk(),
                ticket.getSoTien()
            });
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nhanXeBtn = new javax.swing.JButton();
        traxeBtn = new javax.swing.JButton();
        dangkyVTBtn = new javax.swing.JButton();
        taiKhoanBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        dangXuatTxt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        chaoMungTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        veTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sdtTxt = new javax.swing.JTextField();
        suaBtn = new javax.swing.JButton();
        xoaBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        loaiXeTxt = new javax.swing.JTextField();
        mauXeTxt = new javax.swing.JTextField();
        maVeTxt = new javax.swing.JTextField();
        tenKHTxt = new javax.swing.JTextField();
        biensoXeTxt = new javax.swing.JTextField();
        themBtn = new javax.swing.JButton();
        lammoiBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1686, 606));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        nhanXeBtn.setBackground(new java.awt.Color(254, 183, 19));
        nhanXeBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nhanXeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_sedan_32px.png"))); // NOI18N
        nhanXeBtn.setText("Nhận Xe");
        nhanXeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nhanXeBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nhanXeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanXeBtnActionPerformed(evt);
            }
        });

        traxeBtn.setBackground(new java.awt.Color(254, 183, 19));
        traxeBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        traxeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_car_theft_32px.png"))); // NOI18N
        traxeBtn.setText("Trả Xe");
        traxeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        traxeBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        traxeBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        traxeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traxeBtnActionPerformed(evt);
            }
        });

        dangkyVTBtn.setBackground(new java.awt.Color(254, 183, 19));
        dangkyVTBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dangkyVTBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_membership_card_32px_1.png"))); // NOI18N
        dangkyVTBtn.setText("Đăng Kí Vé Tháng");
        dangkyVTBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dangkyVTBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dangkyVTBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dangkyVTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangkyVTBtnActionPerformed(evt);
            }
        });

        taiKhoanBtn.setBackground(new java.awt.Color(254, 183, 19));
        taiKhoanBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        taiKhoanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_user_32px_1.png"))); // NOI18N
        taiKhoanBtn.setText("Tài Khoản");
        taiKhoanBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        taiKhoanBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        taiKhoanBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        taiKhoanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taiKhoanBtnActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dangkyVTBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(traxeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nhanXeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taiKhoanBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(nhanXeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(traxeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dangkyVTBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(taiKhoanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator3)
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        dangXuatTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dangXuatTxt.setText("Đăng Xuất");
        dangXuatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangXuatTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setText("Chào mừng Nhân Viên:");

        chaoMungTxt.setBackground(new java.awt.Color(0, 153, 255));
        chaoMungTxt.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        chaoMungTxt.setBorder(null);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chaoMungTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(dangXuatTxt)
                .addGap(27, 27, 27))
            .addComponent(jSeparator2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dangXuatTxt)
                    .addComponent(jLabel2)
                    .addComponent(chaoMungTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        veTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        veTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Vé", "Tên Khách Hàng", "Số Điện Thoại", "Biển Số Xe", "Loại Xe", "Màu Xe", "Ngày Đăng Kí"
            }
        ));
        jScrollPane1.setViewportView(veTable);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Đăng Kí Vé Tháng");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Mã Vé :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Số Điện Thoại :");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Biển Số Xe :");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Màu Xe :");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Loại Xe :");

        sdtTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        suaBtn.setBackground(new java.awt.Color(254, 183, 19));
        suaBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        suaBtn.setText("Sửa");
        suaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaBtnActionPerformed(evt);
            }
        });

        xoaBtn.setBackground(new java.awt.Color(254, 183, 19));
        xoaBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        xoaBtn.setText("Xóa");
        xoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Tên Khách Hàng :");

        loaiXeTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        mauXeTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        maVeTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tenKHTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        biensoXeTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        themBtn.setBackground(new java.awt.Color(254, 183, 19));
        themBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        themBtn.setText("Thêm");
        themBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBtnActionPerformed(evt);
            }
        });

        lammoiBtn.setBackground(new java.awt.Color(254, 183, 19));
        lammoiBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lammoiBtn.setText("Làm Mới");
        lammoiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lammoiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(377, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(359, 359, 359))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(themBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(suaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(xoaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(lammoiBtn)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tenKHTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(maVeTxt)
                            .addComponent(sdtTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mauXeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(loaiXeTxt)
                            .addComponent(biensoXeTxt))))
                .addGap(93, 93, 93))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maVeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(biensoXeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tenKHTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(loaiXeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sdtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(mauXeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lammoiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void xoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBtnActionPerformed
        int selectedIndex = veTable.getSelectedRow();
        if (selectedIndex >= 0) {
            VeThangDTO ticket = dataList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this item?");

            if (option == 0) {
                VeThangDAO.delete(ticket.getMaVe());
                showData();
                lammoiBtnActionPerformed(evt);
                xoaBtn.setEnabled(false);
                suaBtn.setEnabled(false);
            }
        }
    }//GEN-LAST:event_xoaBtnActionPerformed

    private void themBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBtnActionPerformed
        String ticketId = maVeTxt.getText();
        String customerName = tenKHTxt.getText();
        String phoneNumber = sdtTxt.getText();
        String licensePlate = biensoXeTxt.getText();
        String vehicleType = loaiXeTxt.getText();
        String vehicleColor = mauXeTxt.getText();
        LocalDate currentDate = LocalDate.now();
        int tien;
        VeThangDTO ticket = new VeThangDTO();
        if (vehicleType.equals("Xe Máy")) {
            tien = 70000;
            ticket = new VeThangDTO(ticketId, customerName, phoneNumber, licensePlate, vehicleType, vehicleColor, currentDate, 70000);
        } else {
            tien = 100000;
            ticket = new VeThangDTO(ticketId, customerName, phoneNumber, licensePlate, vehicleType, vehicleColor, currentDate, 200000);
        }
        TongVeThangDTO tk = new TongVeThangDTO(ticketId, customerName, phoneNumber, licensePlate, vehicleType, vehicleColor, currentDate, tien);
        TongVeThangDAO.insert(tk);
        HoaDonVT billsFrame = new HoaDonVT(ticket);
        billsFrame.setBillActionListener(new BillActionListener() {
            @Override
            public void onConfirm(VeThangDTO ticket) {
                VeThangDAO.insert(ticket); 
                showData(); 
                lammoiBtnActionPerformed(evt); 
            }

            @Override
            public void onCancel() {
            }
        });
        billsFrame.setVisible(true);
    }//GEN-LAST:event_themBtnActionPerformed

    private void suaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaBtnActionPerformed
        String ticketId = maVeTxt.getText();
        String customerName = tenKHTxt.getText();
        String phoneNumber = sdtTxt.getText();
        String licensePlate = biensoXeTxt.getText();
        String vehicleType = loaiXeTxt.getText();
        String vehicleColor = mauXeTxt.getText();
        VeThangDTO ticket = new VeThangDTO(ticketId, customerName, phoneNumber, licensePlate, vehicleType, vehicleColor);
        VeThangDAO.update(ticket);
        showData();
        lammoiBtnActionPerformed(evt);
        xoaBtn.setEnabled(false);
        suaBtn.setEnabled(false);
    }//GEN-LAST:event_suaBtnActionPerformed

    private void lammoiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lammoiBtnActionPerformed
        maVeTxt.setText("");
        tenKHTxt.setText("");
        sdtTxt.setText("");
        loaiXeTxt.setText("");
        biensoXeTxt.setText("");
        mauXeTxt.setText("");
    }//GEN-LAST:event_lammoiBtnActionPerformed

    private void nhanXeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanXeBtnActionPerformed
        new NhanXe(ten).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nhanXeBtnActionPerformed

    private void dangkyVTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangkyVTBtnActionPerformed
        new DangKyVeThang(ten).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dangkyVTBtnActionPerformed

    private void taiKhoanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taiKhoanBtnActionPerformed
        new TaiKhoan(ten).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_taiKhoanBtnActionPerformed

    private void dangXuatTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangXuatTxtActionPerformed
        new DangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dangXuatTxtActionPerformed

    private void traxeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traxeBtnActionPerformed
        new TraXe(ten).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_traxeBtnActionPerformed

    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biensoXeTxt;
    private javax.swing.JTextField chaoMungTxt;
    private javax.swing.JButton dangXuatTxt;
    private javax.swing.JButton dangkyVTBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton lammoiBtn;
    private javax.swing.JTextField loaiXeTxt;
    private javax.swing.JTextField maVeTxt;
    private javax.swing.JTextField mauXeTxt;
    private javax.swing.JButton nhanXeBtn;
    private javax.swing.JTextField sdtTxt;
    private javax.swing.JButton suaBtn;
    private javax.swing.JButton taiKhoanBtn;
    private javax.swing.JTextField tenKHTxt;
    private javax.swing.JButton themBtn;
    private javax.swing.JButton traxeBtn;
    private javax.swing.JTable veTable;
    private javax.swing.JButton xoaBtn;
    // End of variables declaration//GEN-END:variables
}
